apiVersion: v1
kind: Service
metadata:
  name: flask-app-prediction
  labels:
    app.kubernetes.io/name: flask-app-prediction
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: flask-app-prediction
    app.kubernetes.io/component: backend