apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-prediction
  labels:
    app.kubernetes.io/name: flask-app-prediction
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-app-prediction
      app.kubernetes.io/component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flask-app-prediction
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: minikube-flask-app-prediction
        image: docker.io/uavsystems/flask-app-prediction:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80