version: "3.9"
services:
  flask-app-prediction:
    image: $dockerpath:latest
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/repo
      # - /var/run/docker.sock:/var/run/docker.sock
    environment:
      FLASK_ENV: development      