AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template for Cloud9 setups. Creates a Cloud9
  development environment.
Parameters:
  workflowID:
    Description: Deployment workflow ID
    Type: String
  Cloud9InstanceType:
    Description: Cloud9 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
      - t3.medium
    ConstraintDescription: Must be a valid Cloud9 instance type
  AutomaticStopTimeMinutes:
    Description: Number of minutes until the running instance is shut down after the environment was last used.
    Type: String
    Default: 30
  ConnectionType:
    Description: Connection type used for connecting to an Amazon EC2 environment
    Type: String
    Default: "CONNECT_SSH"
  EnvDescription:
    Description: Description of the environment to create.
    Type: String
    Default: "AWS Cloud9 Instance"
  ImageId:
    Description:  Identifier for the Amazon Machine Image (AMI) 
    Type: AWS::EC2::Image::Id
    Default: ubuntu-18.04-x86_64
  InstanceUser:
    Description: User used to boot ec2 instance
    Type: String
    NoEcho: True
    Default: "ubuntu"
  GitRepoName:
    Description: Git repository name to be cloned.
    Type: String
    Default: "oliviermbida/devops-microservices-aws-kubernetes"
  GitUserName:
    Description: Git username 
    Type: String
    Default: "oliviermbida"
  GitUserEmail:
    Description: Git user email
    Type: String
    Default: ""
  GithubSshKeyName:
    Description: Github ssh key name stored in secretsmanager
    NoEcho: True
    Type: String
    Default: "githubsshkey"
Resources:
################## SSM BOOTSRAP HANDLER ###############
  Cloud9OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Name
          Value: !Sub s3-Cloud9-${workflowID}

  Cloud9SSMDocument: 
    Type: AWS::SSM::Document
    Properties: 
      Tags:
        - Key: Environment
          Value: !Sub Cloud9-${workflowID}
      DocumentFormat: YAML
      DocumentType: Command
      Content: 
        schemaVersion: '2.2'
        description: Bootstrap Cloud9 Instance
        mainSteps:
        - action: aws:runShellScript
          name: Cloud9bootstrap
          inputs:
            runCommand:
            - "#!/bin/bash"
            - date
            - echo LANG=en_US.utf-8 >> /etc/environment
            - echo LC_ALL=en_US.UTF-8 >> /etc/environment
            - !Sub EC2_USER=${InstanceUser}
            - !Sub SSH_KEY=${GithubSshKeyName}
            - !Sub GIT_REPO=${GitRepoName}
            - !Sub GIT_USER=${GitUserName}
            - !Sub GIT_EMAIL=${GitUserEmail}
            - . /home/$EC2_USER/.bashrc
            - echo '=== Configure ssh agent ==='
            - aws ssm get-parameter --name /aws/reference/secretsmanager/$SSH_KEY --with-decryption --output text --query "Parameter.Value" > "~/.ssh/id_ed25519"
            - chmod 0700 "~/.ssh/id_ed25519"
            - echo "Host github.com" >> ~/.ssh/config
            - echo "    User $GIT_USER" >> ~/.ssh/config
            - echo "    IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config
            - chmod 0700 "~/.ssh/config"
            - echo '=== Clone git repository ==='
            - git clone git@github.com:$GIT_REPO.git
            - echo '=== Install Circleci cli ==='
            - curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh
            - sudo -H -u $EC2_USER bash -c "./install.sh"
            - echo "Bootstrap completed with return code $?"
  Cloud9BootstrapAssociation: 
    Type: AWS::SSM::Association
    Properties: 
      Name: !Ref Cloud9SSMDocument
      OutputLocation: 
        S3Location:
          OutputS3BucketName: !Ref Cloud9OutputBucket
          OutputS3KeyPrefix: bootstrapoutput
      Targets:
        - Key: tag:SSMBootstrap
          Values:
          - Active
  Cloud9Instance:
    DependsOn: Cloud9BootstrapAssociation
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      Description: 
        Ref: EnvDescription 
      AutomaticStopTimeMinutes: 
        Ref: AutomaticStopTimeMinutes
      ConnectionType: 
        Ref: ConnectionType
      InstanceType:
        Ref: Cloud9InstanceType
      ImageId:
        Ref: ImageId
      Name: !Sub ${AWS::StackName}
      Tags: 
        - 
          Key: SSMBootstrap
          Value: Active
        - 
          Key: Environment
          Value: !Sub Cloud9-${workflowID}

Outputs: 
  Cloud9IDE:
    Value:
      Fn::Join:
      - ''
      - - https://
        - Ref: AWS::Region
        - ".console.aws.amazon.com/cloud9/ide/"
        - Ref: Cloud9Instance
        - "?region="
        - Ref: AWS::Region