Description: >
  Nested top level Stack Update version 1.0
  Security update
Parameters:
  workflowID:
    Description: Deployment workflow ID
    Type: String

Resources:
  compliance:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        workflowID: !Ref workflowID
      TemplateURL: security.yaml
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-compliance-${workflowID}'